#!/bin/bash 

set -o pipefail

if [ "$#" -lt "1" ] ; then 
	echo "Incorrect usage ! Example:" 
	echo './countdown.sh -d  "Jun 10 2011 16:06"' 
	echo 'or' 
	echo './countdown.sh -m  90' 
	exit 1 
fi 
 
start=`date +%s` 
 
if [ "$1" = "-d" ] ; then 
	until=`date -d "$2" +%s` 
	seconds=`expr $until - $start` 
	if [ $seconds -lt 1 ]; then 
		echo "$2 is already history !" 
	fi 
fi 
 
if [ "$1" = "-m" ] ; then 
	seconds=`expr $2 \* 60`
	if [ $seconds -lt 1 ]; then 
		echo "$2 is already history !" 
	fi 
fi 

if [ "$1" = "-s" ] ; then 
	seconds=$2 
	if [ $seconds -lt 1 ]; then 
		echo "$2 is already history !" 
	fi 
fi 

if [ "$1" = "-p" ] ; then 
	seconds=`expr 60 \* 22 + 30` 
	if [ $seconds -lt 1 ]; then 
		echo "$2 is already history !" 
	fi 
fi 
 
end=`expr $start + $seconds`
now=`date +%s` 

while [ $end -gt $now ]; do 
	clear 
	sec_rem=`expr $end - $now`
	seconds=`expr $sec_rem % 60` 
	sec_rem=`expr $sec_rem - $seconds` 
	minutes=`expr $sec_rem % 3600 / 60` 
	sec_rem=`expr $sec_rem - $minutes` 
	hours=`expr $sec_rem % 86400 / 3600` 
	echo $hours":"$minutes":"$seconds
	now=`date +%s` 

	sleep 1
done
notify-send "Time is up" "       "
play ~/projects/countdown/sound.mp3 </dev/null &>/dev/null &

printf "\n"
